### ISSUE TITLE
os path issue on windows

### ISSUE THREAD

**Issue by andrewschmidt-a** [andrewschmidt-a/azure-adventure#2]
The first actual exercise crashes at os.path.join

Traceback (most recent call last):
  File ".\index.py", line 25, in <module>
    locals()[checkpoint[0]].main(checkpoint[1], common)
  File "C:\git\azure-adventure\modules\intro\__init__.py", line 86, in main
    eval("checkpoint"+str(checkpoint)+"()")
  File "<string>", line 1, in <module>
  File "C:\git\azure-adventure\modules\intro\__init__.py", line 49, in checkpoint2
    utils.openCode(os.path.join(dir_path, "workspace"))
  File "C:\git\azure-adventure\common\__init__.py", line 32, in openCode
    subprocess.call(["code", path])
  File "c:\users\a90q9zz\appdata\local\programs\python\python37\lib\subprocess.py", line 317, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\users\a90q9zz\appdata\local\programs\python\python37\lib\subprocess.py", line 769, in __init__
    restore_signals, start_new_session)
  File "c:\users\a90q9zz\appdata\local\programs\python\python37\lib\subprocess.py", line 1172, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by andrewschmidt-a** [comment]
https://github.com/andrewschmidt-a/azure-adventure/pull/4
